### ISSUE TITLE
Algorithm Completion, Fixes, and Enhancements, and Example contexts

### ISSUE THREAD

**Issue by Wind4Greg** [w3c/vc-di-eddsa#30]
While working through test vectors for the draft and receiving comments on those test vectors we came across some ambiguities, missing pieces, and mistakes (only one) in the Algorithms section of the draft. In addition, based on concerns about the `@context` field in the test vectors I did a review of the examples (non test vectors) in the draft and found some issues/questions/recommendations. I've summarized my findings below and depending on outcomes and issue pull requests and deemed necessary.

## Restructure, enhance and fix the Algorithms section. 

New outline that is more in line with the actual processing steps:

* 3.1 Unsecured Document Transformation (rather than just "Transformation" to be clear)
* 3.2 Proof Configuration Generation (rather than just "Proof Configuration" to be clear)
* 3.3 Proof Configuration Transformation (new section on how to canonicalize proof configuration)
* 3.4 Hashing (need to fix order of concatenated hashes, this is an **error**!, current document does not reflect deployed implementations)
* 3.5 Proof Generation (enhance explanation with explanation of use of previous steps feeding into signature algorithm)
* 3.6 Proof Verification (This is incomplete, it cites data integrity which does not furnish enough information. In particular does not cover recreating the proof configuration which is needed in verification. enhance with explanation of how to use previous steps 3.1-3.4 in and EdDSA algorithm in verification)

In the new section on "Proof Configuration Transformation" it would be good to explicitly address how `@context` should be handle. I would suggest:

* In the (type: "DataIntegrityProof", cryptosuite: "eddsa-2022") and (type: "Ed25519Signature2020") cases, i.e., those using "RDF Dataset Canonicalization" that the `@context` field from the *unsecured document* is added as a whole to the `proofConfig` being created prior to canonicalization. Note: this may result in a bit of extra `@context` information being added to `proofConfig` that doesn't change the canonical value, but keeps this step simple.
* In the (type: "DataIntegrityProof", cryptosuite: "json-eddsa-2022") case, i.e., using JCS RFC8785, that the `@context` field **not** be added to `proofConfig` since it use is not needed for JCS processing.

## Regularize Context Usage

 `@context`, in examples:

* Example 1 doesn't use `@context` should it?
* Example 2 uses: "https://www.w3.org/ns/did/v1", "https://w3id.org/security/data-integrity/v1". This **doesn't** canonize at the JSON-LD playground but **does** with a context of just "https://www.w3.org/ns/credentials/v2".
* Example 3 doesn't use `@context` should it?
* Example 4 uses: "https://www.w3.org/ns/did/v1", "https://w3id.org/security/suites/ed25519-2020/v1". This canonizes at the JSON-LD playground and also **works** with just "https://www.w3.org/ns/credentials/v2" as context.
* Example 5 uses: {"title": "https://schema.org/title"}, "https://w3id.org/security/data-integrity/v1" as `@context`. This canonizes at the  JSON-LD playground and **works** with {"title": "https://schema.org/title"}, "https://www.w3.org/ns/credentials/v2"

Hence can we simplify the above to just use the "https://www.w3.org/ns/credentials/v2" reference in the `@context`? If not can someone more expert in JSON-LD contexts write some non-normative text to aid developers trying to implement this specification.

 `@context` in  test vectors

The example for the unsecured document to be used for the generation of all test vectors is shown below. If it should be modified prior to regeneration of the test vectors let me know.

```json
{
    "@context": [
        "https://www.w3.org/ns/credentials/v2",
        "https://www.w3.org/ns/credentials/examples/v2"
    ],
    "id": "urn:uuid:58172aac-d8ba-11ed-83dd-0b3aef56cc33",
    "type": ["VerifiableCredential", "AlumniCredential"],
    "name": "Alumni Credential",
    "description": "A minimum viable example of an Alumni Credential.",
    "issuer": "https://vc.example/issuers/5678",
    "validFrom": "2023-01-01T00:00:00Z",
    "credentialSubject": {
        "id": "did:example:abcdefgh",
        "alumniOf": "The School of Examples"
    }
}
```

**Comment by TallTed** [comment]
I suggest a bit of rewording to be more clear, especially relevant for I18n and such:

* 3.1 Transformation of Unsecured Document
* 3.2 Generation of Proof Configuration
* 3.3 Transformation of Proof Configuration
* 3.4 Hashing
* 3.5 Generation of Proof
* 3.6 Verification of Proof

**Comment by Wind4Greg** [comment]
I was working with an outdated version. Updated my main to match. Saw that the hash ordering has been fixed!

* Still need to complete the "Proof Configuration/Options" step with canonicalization. I don't know about general reordering of algorithm section since there is now a section for each suite. Reviewing in depth now. May just try a small PR to fix this.
* Still need to "Regularize Context Usage" as stated above.
* Still would like to use one example unsecured document to generate all test vectors. Opinions?

**Comment by Wind4Greg** [comment]
Document has been reorganized and algorithm updated. So will close this and open a separate issue on example contexts.
