### ISSUE TITLE
Necessary adjustments to the security vocabulary

### ISSUE THREAD

**Issue by iherman** [w3c/vc-di-eddsa#33]
_If_ my interpretation in #32 is correct, there are some adjustments to be made to the [data integrity vocabulary](https://w3id.org/security) document, namely:

- A new class `Multikey` should be added, presumably as a subclass of `VerificationMethod`
- A new property `privateKeyMultibase` should be added, as a counterpart to the (already existing) `publicKeyMultibase` property
- The `Ed255Signature2020` should be marked as `deprecated` (note: the `Ed2559VerificationKey2020` class was already set to deprecated before, but that was artificial and simply reflected the fact that the class is not even mentioned in the Data Integrity spec)

Obviously, I am happy to create a relevant PR, but I wanted to check this first.

**Comment by msporny** [comment]
> * A new class `Multikey` should be added, presumably as a subclass of `VerificationMethod`

+1

> * A new property `privateKeyMultibase` should be added, as a counterpart to the (already existing) `publicKeyMultibase` property

-1 (and this is controversial) -- I don't think we should make it easy to publish private key material because... it's private key  material and should never be sent outside the device in which it is operating (unless encrypted, and even then, sharing private keys is bad). You can just have people locally express this information as a JSON data structure.

> * The `Ed255Signature2020` should be marked as `deprecated` (note: the `Ed2559VerificationKey2020` class was already set to deprecated before, but that was artificial and simply reflected the fact that the class is not even mentioned in the Data Integrity spec)

+1

**Comment by iherman** [comment]
> 
> > * A new property `privateKeyMultibase` should be added, as a counterpart to the (already existing) `publicKeyMultibase` property
> 
> -1 (and this is controversial) -- I don't think we should make it easy to publish private key material because... it's private key material and should never be sent outside the device in which it is operating (unless encrypted, and even then, sharing private keys is bad). You can just have people locally express this information as a JSON data structure.
> 

Even as a layperson I understand the reasoning, but then shouldn't we immediately remove the `privateKeyPem` property from the vocabulary specification (even though it is deprecated)? (Of should we leave that for the upcoming big vocabulary cleanup?)

**Comment by dmitrizagidulin** [comment]
> Even as a layperson I understand the reasoning, but then shouldn't we immediately remove the `privateKeyPem` property from the vocabulary specification (even though it is deprecated)? (Of should we leave that for the upcoming big vocabulary cleanup?)

Yeah, if @msporny does not object, I propose we leave it for the general vocab cleanup.

**Comment by iherman** [comment]
> 
> Yeah, if @msporny does not object, I propose we leave it for the general vocab cleanup.

I would certainly prefer that. The security vocabulary cleanup is still ahead of us (big time!) and it may be the gathering point for a number of terms that are not necessarily defined in the security spec per se, but also in one of the `vc-di-*` specs.

**Comment by iherman** [comment]
I believe this is also covered by https://github.com/w3c/vc-data-integrity/pull/127

**Comment by iherman** [comment]
Actually... the repo marks the `ED2559***2020` classes as bona fide terms (and not deprecated) because they appear in an Appendix that is not marked as informative. Which makes those definitions normative, and then the vocabulary should not deprecate it.

***If*** the Appendix is set to informative, then I am happy to mark those terms as deprecated in  https://github.com/w3c/vc-data-integrity/pull/127

**Comment by iherman** [comment]
This can be closed if and when https://github.com/w3c/vc-data-integrity/pull/127 is merged.

**Comment by msporny** [comment]
PR https://github.com/w3c/vc-data-integrity/pull/127 has been merged. Closing.
