### ISSUE TITLE
Is Example 15 / 16 correct?

### ISSUE THREAD

**Issue by HelgeKrueger** [w3c/vc-di-eddsa#38]
I just tried to implement the Ed25519Signature2020 in python, and hit the following block, while trying to reproduce https://w3c.github.io/vc-di-eddsa/#representation-ed25519signature2020

Everything works fine until I sign the combined hash. Then I get a different result:

```python
expectation = "473fb02a4aaf5863a2ef33f104bd55617e40907bc311e29e87278d15d7596f201639f41ec0e00db11159e9139f673d9257558e1f0134e1f67ac73f91ed89670b"
my_result = "9da48c66efed97e18281786cdd43e3fd245abbbdfebc9f9ab4cf0e974bb9a80bc3166ec9cf5f2a8e2f1c78a53682f9b7649f32285124b1ade5bd46b667b7620e"
```

I decode the private key via:

```python
from multiformats import multibase, multicodec
from cryptography.hazmat.primitives.asymmetric import ed25519

  decoded = multibase.decode("z3u2en7t5LR2WtQH5PfFqMqwVHBeXouLzo6haApm8XHqvjxq")
  codec, key_bytes = multicodec.unwrap(decoded)
  assert codec.name == "ed25519-priv"
  private_key = ed25519.Ed25519PrivateKey.from_private_bytes(key_bytes)
```

and sign the combined hash via

```python
signed_hex = private_key.sign(combined_hash.encode("ascii")).hex()
```

The base58btc encoding also turns out wrong.

Does someone spot where my mistake is? Or can quickly confirm example 15/16 are correct?

**Comment by msporny** [comment]
```js
signed_hex = private_key.sign(combined_hash.encode("ascii")).hex()
```
^^^ That line looks strange... I haven't looked up the API, but it looks like you're encoding the combined_hash as ASCII and then signing that, when what you should be doing is signing the raw bytes of the hash. IOW, remove `.encode("ascii")` and see what happens. That said, a gist of your code would be easier to pick through.

You might try taking a look at @Wind4Greg's step by step code:

https://github.com/Wind4Greg/EdDSA-Test-Vectors/blob/master/DataIntegrityCreate.js

/cc @Wind4Greg Thoughts on the above since they're your test vectors?

**Comment by msporny** [comment]
Out of curiosity, @HelgeKrueger -- are you doing this implementation for some ActivityPub thing? ... or something else? 

Once you get your implementation done, are you interested in testing it against the test suite we're creating?

**Comment by HelgeKrueger** [comment]
> You might try taking a look at @Wind4Greg's step by step code:
>
> https://github.com/Wind4Greg/EdDSA-Test-Vectors/blob/master/DataIntegrityCreate.js

I found the mistake. Thanks. I'm leaving the issue open to answer your other question later.

**Comment by HelgeKrueger** [comment]
> Once you get your implementation done, are you interested in testing it against the test suite we're creating?

Sure, I've uploaded how far I am at https://codeberg.org/helge/vc-di-eddsa-python
The JCS version works. For the other one, I think I need to check what context to use or something. Is my reading of the document correct that the "Ed25519Signature2020" will be replaced by "DataIntegrityProof"?

---

My goal is to eventually use this together with ActivityPub, yes.

**Comment by Wind4Greg** [comment]
Hi all, glad you verified. I was doing things in python too for a while see [Verifying Verifiable Credetials](https://www.grotto-networking.com/blog/posts/jsonldProofs.html) and [DIDs and number representations in Python](https://www.grotto-networking.com/blog/posts/DID_Key.html). But now mostly doing the test vectors in JavaScript. 
Cheers
Greg

**Comment by HelgeKrueger** [comment]
Hi @msporny @Wind4Greg

I used this for one of the ActivityPub relevant use cases:  https://codeberg.org/helge/vc-di-eddsa-python/src/branch/main/test_fep_c390.py There are two test cases, first with @context second one without.

Question: 

- Should "json-eddsa-2022" work without @context? 
- If yes, what about introducing "json-ld-eddsa-2022", which involves performing [Expandsion](https://www.w3.org/TR/json-ld-api/#expansion) before signing. This should still lead to a well defined algorithm.

**Comment by msporny** [comment]
> > Once you get your implementation done, are you interested in testing it against the test suite we're creating?
> 
> Sure, I've uploaded how far I am at https://codeberg.org/helge/vc-di-eddsa-python The JCS version works. 

Wonderful! Thank you! We expect to have the JCS test suites ready by some time over the summer. You don't need to be blocked by that fact  :), just letting you know when we expect the jcs-eddsa-2022 test suite to materialize.

> For the other one, I think I need to check what context to use or something. Is my reading of the document correct that the "Ed25519Signature2020" will be replaced by "DataIntegrityProof"?

Yes, correct. `DataIntegrityProof` is what we're trying to get the community to converge to.

I wouldn't implemented `Ed25519Signature2020` if you're doing a new implementation (unless you have someone else that you're trying to integrate with that is using `Ed25519Signature2020` (which I doubt you do, `Ed25519Signature2020` has mostly been used in the retail sector). 

> My goal is to eventually use this together with ActivityPub, yes.

That's great, we're big fans of ActivityPub (as well as usage of Data Integrity in that context). Are you working with @silverpill (who authored FEP_c390, IIRC) on this?

**Comment by silverpill** [comment]
@msporny We are working on different Fediverse projects, but I hope our software will be able to interoperate. I'm planning to implement `jcs-eddsa-2022` too (#41).

**Comment by msporny** [comment]
> @msporny We are working on different Fediverse projects, but I hope our software will be able to interoperate. I'm planning to implement `jcs-eddsa-2022` too (#41).

Even better news, @silverpill! :)

We (Digital Bazaar) are planning an implementation as well... so that means that we'll have at least 3 implementations right out of the gate for something that we were worried was only going to get 1 implementation.

**Comment by Wind4Greg** [comment]
We've got a complete set of test vectors now. Any issues remaining?

**Comment by HelgeKrueger** [comment]
I've started taking another look.

1. Example 20 is poorly formatted in https://www.w3.org/TR/vc-di-eddsa/#example-canonical-credential-without-proof-0
2. [Example 28](https://w3c.github.io/vc-di-eddsa/#example-signed-credential-0): Signed Credential still uses json-eddsa-2022 instead of jcs-eddsa-2022

Same in Example 20.
[Section 3.2. is jcs-eddsa-2022](https://w3c.github.io/vc-di-eddsa/#jcs-eddsa-2022)

 Which one is correct?

**Comment by msporny** [comment]
@HelgeKrueger wrote:
> 2\. [Example 28](https://w3c.github.io/vc-di-eddsa/#example-signed-credential-0): Signed Credential still uses json-eddsa-2022 instead of jcs-eddsa-2022

@HelgeKrueger, which one would you prefer? @silverpill, thoughts from you as well? The Working Group is trying to decide on the naming convention and had suggested "json" initially, but some want it to be "jcs". We are trying to reduce as many parameters that average developers might not understand (like, will they really understand what 'jcs' is vs. 'json'?). One suggestion has been names like "fedi-sign-2023" vs. "jcs-eddsa-2022" (that is, names that convey to developers that they're using the right thing vs. some crammed together acronym that they have to look up). What naming do you think would be easiest for fediverse developers to grasp and use?

**Comment by msporny** [comment]
@HelgeKrueger and @silverpill, both of you might also want to be tracking this cryptosuite as well (the NIST approved, hardware security module version of eddsa-2022... if you have eddsa-2022 working, supporting ECDSA is an easy step): https://www.w3.org/TR/vc-di-ecdsa/#jcs-ecdsa-2019

I say this because large organizations and governments are getting very interested in deploying ActivityPub, digitally signed inbox/outbox messages, and ECDSA tends to be a requirement from those sorts of organizations.

**Comment by silverpill** [comment]
@msporny 

>Working Group is trying to decide on the naming convention and had suggested "json" initially, but some want it to be "jcs"

I prefer `jcs-`, as it's more descriptive and it helps me explain to others what my software is doing. I think in ActivityPub world the choice of canonicalization algorithm is quite important; it is not some minor detail that can be hidden from a developer. On the contrary, it might be a good idea to rename `eddsa-2022` to something like `ld-eddsa-2022` to articulate the difference between two cryptosuites.

>https://www.w3.org/TR/vc-di-ecdsa/#jcs-ecdsa-2019

Among those who are interested in implementing data integrity proofs in Fediverse, there seems to be a consensus that EdDSA is the best option.
But yes, supporting ECDSA would be an easy step.

**Comment by Wind4Greg** [comment]
On example 20 being *poorly formatted*. This is the output of the JCS canonicalization algorithm so is just one long string. I imported the  test vector directly via ReSpec. What would you suggest? I could look into some CSS for wrapping or other mechanism.

**Comment by dmitrizagidulin** [comment]
> On example 20 being _poorly formatted_. This is the output of the JCS canonicalization algorithm so is just one long string. I imported the test vector directly via ReSpec. What would you suggest? I could look into some CSS for wrapping or other mechanism.

Yeah, normally I would be for pretty-print formatting too, but in this particular case, since it's a direct output of the JCS algorithm, we need it to be easily copy-able as is, without un-formatting. So, I suggest we keep it as is.

**Comment by HelgeKrueger** [comment]
I have now added two Gherkin features for vc-di-eddsa at https://codeberg.org/helge/fediverse-features/src/branch/main/w3c

As I've used jcs-eddsa-2022 as the cryptosuite name, the values are different from the example in the specification.

**Comment by msporny** [comment]
> I have now added two Gherkin features for vc-di-eddsa

Wonderful!

> As I've used jcs-eddsa-2022 as the cryptosuite name, the values are different from the example in the specification.

Just a heads up that we're trying to finalize the names for the cryptosuites in the next month or so. Your input (and @silverpill's input) here would be helpful so we only have to do the rename once:

https://github.com/w3c/vc-data-integrity/issues/38

**Comment by msporny** [comment]
@HelgeKrueger I believe we can close this issue (a lot has happened since it was first opened, so it feels like this issue has been overtaken by events)? If not, what else needs to be done?
