### ISSUE TITLE
jcs-eddsa-2022 review

### ISSUE THREAD

**Issue by silverpill** [w3c/vc-di-eddsa#41]
The description of `jcs-eddsa-2022` cryptosuite (**3.2 jcs-eddsa-2022**) refers to section **3.1.5 Proof Configuration (eddsa-2022)** which contains:

>8. Set proofConfig.context to unsecuredDocument.context

Is this step necessary for `jcs-eddsa-2022`?

>9. Let canonicalProofConfig be the result of applying the Universal RDF Dataset Canonicalization Algorithm [[RDF-CANON](https://w3c.github.io/vc-di-eddsa/#bib-rdf-canon)] to the proofConfig.

Shouldn't this step be replaced with JCS canonicalization?

(These steps were introduced in https://github.com/w3c/vc-di-eddsa/pull/31)

Also, there's an incorrect cryptosuite name in section **3.2 jcs-eddsa-2022**, step 4. I made a branch with a fix https://github.com/silverpill/vc-di-eddsa/pull/1 (couldn't make a pull request against this repo).

**Comment by Wind4Greg** [comment]
Yes. Step 8 is unneeded and Step 9 needs to use JCS. That is what I assumed when writing [this code](https://github.com/Wind4Greg/EdDSA-Test-Vectors/blob/master/JCSDataIntegrityVerify.js) to generate test vectors. Did you want to write the PR?
Cheers Greg

**Comment by silverpill** [comment]
Thank you for clarification!
Not sure if I'm allowed to make PRs. I would appreciate if you update the spec.

**Comment by silverpill** [comment]
The spec has been corrected. Closing
