### ISSUE TITLE
Security Considerations: Provable Security and Ed25519 Libraries

### ISSUE THREAD

**Issue by Wind4Greg** [w3c/vc-di-eddsa#45]
It turns out that after EdDSA Ed25519 signature adoption, rigorous proofs of its security properties were made, but some of these desirable security properties only apply if some relatively straight forward checks are enforced during verification. 

However not all signature libraries for EdDSA Ed25519 perform these checks. Here is some text mostly from the papers explaining the security properties that can be proven and why they are desirable. In addition,  the paper's authors provide test vectors on GitHub to help test signature libraries for some edge cases (only 12 tests in total). Might we want to capture those in this specification as an appendix? Below is some potential starting text. Opinions on how much guidance we should supply on this issue? For a more complete over view see the authors [presentation this year to NIST](https://csrc.nist.gov/Presentations/2023/crclub-2023-03-08).

## Ed25519 Provable Security and Library Implementation Reality

Digital signatures may exhibit a number of desirable cryptographic properties among these are (using the definitions from reference 2 below):

**EUF-CMA** (*existential unforgeability under chosen message attacks*) is usually the minimal security property required of a signature scheme. It guarantees that any efficient adversary who has the public key $pk$ of the signer and received an arbitrary number of signatures on messages of its choice (in an adaptive manner): $\{m_i, \sigma_i\}_{i=1}^N$, cannot output a valid signature $\sigma^∗$ for a new message $m^∗ \notin \{m_i\}_{i=1}^N$ (except with negligible probability). In case the attacker outputs a valid signature on a new message: $(m^∗, \sigma^∗)$, it is called an *existential forgery*.

**SUF-CMA** (*strong unforgeability under chosen message attacks*) is a stronger notion than *EUF-CMA*. It guarantees that for any efficient adversary who has the public key $pk$ of the signer and received an arbitrary number of signatures on messages of its choice: $\{mi, σi\}_{i=1}^N$, it cannot output a new valid signature pair $(m^∗, \sigma^∗)$, s.t. $(m^∗, \sigma^*) \notin \{m^i, σ^i\}_{i=1}^N$ (except with negligible probability). Strong unforgeability implies that an adversary cannot only sign new messages, but also cannot find a new signature on an old message.

**Binding signature** (BS) We say that a signature scheme is *binding* if no efficient signer can output a tuple $[pk, m, m^\prime, \sigma]$, where both $(m, \sigma)$ and $(m^\prime, \sigma)$ are valid message signature pairs under the public key $pk$ and $m \ne m^\prime$ (except with negligible probability). A binding signature makes it impossible for the signer to claim later that it has signed a different message, the signature *binds* the signer to the message.

**Strongly Binding signature** (SBS) Certain applications may require a signature to not only be binding to the message but also be binding to the public key. We say that a signature scheme is strongly-binding if any efficient signer can not output a tuple $[pk, m, pk^\prime, m^\prime, \sigma]$, where $(m, \sigma)$ is a valid signature for the public key $pk$ and $(m^\prime, \sigma)$ is a valid signature for the public key $pk^\prime$ and either $m^\prime \ne m$ or $pk \ne pk^\prime$, or both (except with negligible probability).

It was recently proven in reference 1 and 2 that EdDSA with curve Ed25519 can posses all these desirable cryptographic properties but only if sufficient input validation testing is performed when verifying an Ed25519 based signature. In particular to a achieve the *SUF* property all validation tests checks specified in RFC8032 must be performed. In addition to achieve the *SBS* property public keys which are elliptic curve points of "small order" are invalid and must be rejected.

The validation checks of RFC8032 and the "small order point" checks have been incorporated into some Ed25519 implementations recently, however as shown in reference 2 many libraries have not implemented these validation checks. Since these checks are either part of established signature standard (RFC8032) or relatively minimal (there are only eight canonical small order points to check for) it is strongly recommended that implementers of this specification choose a signature library satisfying these  conditions. Test vectors to test a signature library can be found at [GitHub: ed25519-speccheck](https://github.com/novifinancial/ed25519-speccheck)

### References

1. [The Provable Security of Ed25519: Theory and Practice](https://eprint.iacr.org/2020/823), 2020, Jacqueline Brendel, Cas Cremers, Dennis Jackson, and Mang Zhao.
2. K. C. Garillot François and V. Nikolaenko, [Taming the many EdDSAs](https://eprint.iacr.org/2020/1244), 2020 and accepted to SSR Conference October 2020.
3. [RFC8032: Edwards-Curve Digital Signature Algorithm (EdDSA)](https://www.rfc-editor.org/rfc/rfc8032)

**Comment by Wind4Greg** [comment]
**Update**: 

I was able to get a hold of one of the papers authors via a GitHub issue: https://github.com/MystenLabs/ed25519-unsafe-libs/issues/22. They are fine with us quoting definitions and test vectors. They have also written some work on dangers of some Ed25519 APIs which might also be good to mention in the *security considerations* section.

**Proposal** for *security considerations* section:

1. Explain EdDSA Ed25519 provable security properties.
2. Explain additional validation tests to ensure highest security
3. Possibly add Ed25519 API cautions
4. Add an appendix with test vectors for EdDSA Ed25519 signatures from https://github.com/novifinancial/ed25519-speccheck to allow developers to quickly assess a Ed25519 library. Note: that this is a single JSON file that is relatively small (just 12 test vectors).

Comments?

**Comment by msporny** [comment]
> Might we want to capture those in this specification as an appendix? 

Yes, we want to capture the concepts in the security considerations section.

Additionally, we will want to add these to the test suite that's in process for vc-di-eddsa.

> Opinions on how much guidance we should supply on this issue?

We should speak to each of the items you outline above in the security considerations section *IF* RFC8032 doesn't already cover them.

> Explain EdDSA Ed25519 provable security properties.

Yes, just a paragraph would do with pointers to the papers or RFCs that further elaborate.

> Explain additional validation tests to ensure highest security

Yes, high-level overview with references to the papers that discuss them in more depth.

> Possibly add Ed25519 API cautions

+1, but not sure which "cautions" you're suggesting. Feel free to go forward with a PR and we can further refine there. Ideally, don't put more than 2-3 paragraphs per PR (as doing more than that can cause the PR to get logjammed).

> Add an appendix with test vectors for EdDSA Ed25519 signatures from https://github.com/novifinancial/ed25519-speccheck to allow developers to quickly assess a Ed25519 library. Note: that this is a single JSON file that is relatively small (just 12 test vectors).

I'm a bit on the fence about this one. I think we should definitely put these tests in the test suite and make it mandatory that you pass all of these tests. Whether or not we also put that in the spec is a bit up in the air. I expect that we could safely also put it in the specification. What we might also want to do, which is where the controversy might come in, is add the tests as normative requirements for verification in the specification to ensure that people are aligned with all of the above.

Let's jut get the guidance in the specification in a non-normative capacity for now and then ratchet the requirements up to normative requirements in a separate PR.
