### ISSUE TITLE
Consider making verification method id to be multicodec (instead of just JWK thumbprint)

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/vc-di-eddsa#5]
Currently:

> The `id` of the verification method SHOULD be the JWK thumbprint calculated from the `publicKeyMultibase` property value according to [MULTIBASE].

It would be great if this SHOULD could be changed to be backwards compatible with how `did:key` method key IDs are formed (using a combination of multibase and multicodec) (this would also match common key id strategy of various ed25519-2018 suite implementations).

So, specifically:

```
MULTIBASE(base-type, MULTICODEC(public-key-type, raw-public-key-bytes))
```

This would require adding an entry to the [multicodec table](https://github.com/multiformats/multicodec/blob/master/table.csv) for "JWK Thumbprint". 

That way, the current "JWK thumbprint" approach would be encoded as:

```
MULTIBASE(<base-type - base64url etc>, MULTICODEC(<jwk thumbprint codec type>, <thumbprint bytes>))
```

But also would enable `did:key`-like

```
MULTIBASE(base58-btc, MULTICODEC(public-key-type, raw-public-key-bytes))
```

@OR13 - would you be open to this approach? (Provided we can add 'JWK Thumbprint' as a multicodec entry?)

**Comment by OR13** [comment]
@dmitrizagidulin that section is wrong... it should be what you described, please open a PR if you have time.

**Comment by dmitrizagidulin** [comment]
@OR13 sure thing, thanks.

**Comment by dmitrizagidulin** [comment]
This has been implemented, closing (since I'm the one that opened the issue).
