### ISSUE TITLE
Remove references to MULTIBASE and MULTICODEC

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-di-eddsa#62]
MULTIBASE and MULTICODEC are not standards.  Please replace uses of them with normative text defining the contents any fields using them.

This is related to https://github.com/w3c/vc-data-integrity/issues/191.

**Comment by msporny** [comment]
PR #63 has been raised to address this issue. This issue will be closed once PR #63 has been merged.

**Comment by msporny** [comment]
PR #63 has been merged, closing.
