### ISSUE TITLE
Fix byte length of `publickKeyMultibase` to 34

### ISSUE THREAD

**Issue by JSAssassin** [w3c/vc-di-eddsa#66]
See - https://github.com/w3c/vc-di-eddsa-test-suite/pull/21#discussion_r1380688724 & https://github.com/w3c/vc-di-eddsa-test-suite/pull/21#discussion_r1380838204

**Comment by msporny** [comment]
PR #67 was raised to address this issue and merged. This issue is now resolved. Closing.
