### ISSUE TITLE
Proof serialization signature doesn't match what vc-data-integrity expects

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-di-eddsa#71]
https://w3c.github.io/vc-di-eddsa/#proof-serialization-eddsa-rdfc-2022 returns a byte sequence, but https://www.w3.org/TR/vc-data-integrity/#add-proof expects the [proof serialization algorithm](https://www.w3.org/TR/vc-data-integrity/#dfn-proof-serialization-algorithm) to return an object with `type`, `verificationMethod`, `proofPurpose`, etc. fields.

**Comment by msporny** [comment]
PR https://github.com/w3c/vc-data-integrity/pull/244 and PR #77 were raised, processed, and merged to address this issue; closing.
