### ISSUE TITLE
Add language clarifying that context injection must happen before canonicalisation

### ISSUE THREAD

**Issue by rflechtner** [w3c/vc-di-eddsa#72]
As it is easy to miss for implementers that the input document must be modified before processing by applying context injection, I think it should explicitly be pointed out. Not doing this in jcs implementations will result in unverifiable proofs.

**Comment by msporny** [comment]
The data integrity specification now points this out explicitly:

https://w3c.github.io/vc-data-integrity/#context-injection

As a result, we are closing this issue as addressed.
