### ISSUE TITLE
Ensure `created` proof option is optional

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-eddsa#73]
The current proof configuration algorithm seems to make `created` required instead of optional, this should be fixed.

**Comment by msporny** [comment]
The `created` property is now optional:

https://w3c.github.io/vc-data-integrity/#proofs

The algorithms still need to be updated to ensure that `created` is optional (it shouldn't throw an error if it isn't specified).

**Comment by Wind4Greg** [comment]
@msporny, whoops, the EdDSA spec is using the "old language" in the *DataIntegrityProof* section. I'll update it by the end of the day PDT to use language like that in the ECDSA spec.

**Comment by msporny** [comment]
PR #86 was raised and merged to address this issue. Closing.
