### ISSUE TITLE
Ensure additional custom proof options provided via `proof` are included in the proof configuration

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-eddsa#74]
When creating a proof, other custom proof fields might be given, but it looks like the proof configuration algorithm will not include these -- and it should.

**Comment by msporny** [comment]
This spec seems to be using the "old language" as well @Wind4Greg -- thoughts?

**Comment by Wind4Greg** [comment]
@msporny, Let me get a PR out to fix on Monday.

**Comment by msporny** [comment]
PR #88 has been merged to address this issue. Closing.
