### ISSUE TITLE
Some examples have the wrong / old context version

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-eddsa#75]
Example 2:
https://w3c.github.io/vc-di-eddsa/#example-an-ed25519-public-key-encoded-as-a-multikey-in-a-controller-document

Needs the context updated from: "https://w3id.org/security/data-integrity/v1" to "https://w3id.org/security/multikey/v1".

Example 6:
https://w3c.github.io/vc-di-eddsa/#example-an-ed25519-digital-signature-expressed-as-a-ed25519signature2020

Needs the context updated from: "https://w3id.org/security/data-integrity/v1" to "https://w3id.org/security/suites/ed25519-2020/v1".

**Comment by filip26** [comment]
[Example 39 - Test Vector](https://www.w3.org/TR/vc-di-eddsa/#example-signed-credential-1) - Ed25519Signature2020 nor the proof itself is defined by the provided contexts

**Comment by msporny** [comment]
PR #85 has been merged to address this issue, closing.
