### ISSUE TITLE
eddsa-jcs-2022 and nested documents

### ISSUE THREAD

**Issue by silverpill** [w3c/vc-di-eddsa#81]
Should any additional steps be performed when nested documents are being secured?

Example:

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/data-integrity/v2"
  ],
  "type": "Create",
  "object": {
    "@context": [
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/data-integrity/v2"
    ],
    "type": "Note",
    "content": "test",
    "proof": {
      "@context": [
        "https://www.w3.org/ns/activitystreams",
        "https://w3id.org/security/data-integrity/v2"
      ],
      "type": "DataIntegrityProof",
      "cryptosuite": "eddsa-jcs-2022"
    }
  },
  "proof": {
    "@context": [
      "https://www.w3.org/ns/activitystreams",
      "https://w3id.org/security/data-integrity/v2"
    ],
    "type": "DataIntegrityProof",
    "cryptosuite": "eddsa-jcs-2022"
  }
}
```

The document with type `Note` is secured first, then it is inserted into the document with type `Create` under the `object` property, then `Create` document is secured too. Here, I'm assuming that #79 will be merged. Some properties are omitted for brevity.

Is the resulting document valid?

**Comment by msporny** [comment]
The Editors met and discussed this issue this past Friday. What you are doing is valid and secure.

> Should any additional steps be performed when nested documents are being secured?

No.

> The document with type Note is secured first, then it is inserted into the document with type Create under the object property, then Create document is secured too. 

That is fine, everything is secured.

> Here, I'm assuming that #79 will be merged. 

Yep, that got merged.

> Is the resulting document valid?

Yep, you're all good.

**Comment by msporny** [comment]
The Editors believe that the usage described is valid and, therefore, no other changes to the specification are required. Closing.
