### ISSUE TITLE
eddsa-rdfc-2022 Transformation passes wrong type to "Deserialize JSON-LD"

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-di-eddsa#87]
https://www.w3.org/TR/vc-di-eddsa/#transformation-eddsa-rdfc-2022 takes a [map](https://infra.spec.whatwg.org/#ordered-map) that is not the result of the [Node Map Generation algorithm](https://www.w3.org/TR/json-ld11-api/#node-map-generation) and passes it to https://www.w3.org/TR/json-ld11-api/#deserialize-json-ld-to-rdf-algorithm, which expects "a [map](https://infra.spec.whatwg.org/#ordered-map) node map, which is the result of the [Node Map Generation algorithm](https://www.w3.org/TR/json-ld11-api/#node-map-generation)".

https://github.com/w3c/json-ld-api/issues/579 reports that this type requirement is unclear, but the discussion there indicates that you're expected to do the extra step in callers.

**Comment by msporny** [comment]
Purely editorial, fixed in 91016be54545682f41da23afdf8b77b90f05c515. /cc @dlongley @davidlehn @gkellogg
