### ISSUE TITLE
Typo in appendix A: `eddsa-rdfc-2022` is wrongly named `edssa-2022`

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/vc-di-eddsa#90]
Hi, I think to have spotted a typo in the first paragraph of appendix A, where `eddsa-rdfc-2022` is wrongly named `edssa-2022`. The link correctly points to `eddsa-rdfc-2022`.

**Comment by iherman** [comment]
Thanks @timothee-haudebourg. I have raised a PR for it in #91.

**Comment by msporny** [comment]
This was fixed in PR #90 (and #91). Closing as addressed.
